Bookstore Web/Models/Company.cs
using System.ComponentModel.DataAnnotations;

namespace Bookstore_Web.Models
{
    public class Company
    {

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string? StreetAddress { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? PostalCode { get; set; }
        public string? PhoneNumber { get; set; }
    }
}

Bookstore Web/Areas/Admin/Controllers/CompanyController.cs
using Bookstore_Web.Data.Repository;
using Bookstore_Web.Data.Repository.IRepository;
using Bookstore_Web.Models;
using Bookstore_Web.Models.ViewModel;
using Bookstore_Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bookstore_Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        
        private readonly ICompanyRepository _CompanyRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CompanyController(ICompanyRepository CompanyRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _CompanyRepository = CompanyRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;

        }
        public IActionResult Index()
        {
            List<Company> CompanyList = _CompanyRepository.GetAll().ToList();
            return View(CompanyList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                _CompanyRepository.Add(company);
                _CompanyRepository.Save();
                TempData["Success"] = "Company Cteated Sussessfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        //public IActionResult Upsert(int? id)
        //{
        //    if(id == null || id == 0)
        //    {
        //        return View();
        //    }
        //    Company Company = _CompanyRepository.Get(u=>u.Id == id);
        //    return View(Company);
        //}
        //[HttpPost]
        //public IActionResult Upsert(Company Company)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (Company.Id == 0)
        //        {
        //            _CompanyRepository.Add(Company);
        //        }
        //        else
        //        {
        //            _CompanyRepository.Update(Company);
        //        }
        //        _CompanyRepository.Save();
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}
        public IActionResult Update(int id)
        {
            Company Companys = _CompanyRepository.Get(u => u.Id == id);
            return View(Companys);
        }
        [HttpPost]
        public IActionResult Update(Company company)
        {
            if (ModelState.IsValid)
            { 
                _CompanyRepository.Update(company);
                _CompanyRepository.Save();
                TempData["Success"] = "Company Updated Sussessfully";
                return RedirectToAction("Index");
            }
            return View(company);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> CompanyList = _CompanyRepository.GetAll().ToList();
            return Json(new { data = CompanyList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var CompanytobeDeleted = _CompanyRepository.Get(u => u.Id == id);
            if (CompanytobeDeleted == null)
            {
                return Json(new { success = false, message = "error while deleting" });
            }
            _CompanyRepository.Remove(CompanytobeDeleted);
            _CompanyRepository.Save();
            return Json(new { success = true, message = "Company deleted" });
        }
        #endregion

    }
}

Bookstore Web/Areas/Admin/Controllers/ProductController.cs
using Bookstore_Web.Data.Repository;
using Bookstore_Web.Data.Repository.IRepository;
using Bookstore_Web.Models;
using Bookstore_Web.Models.ViewModel;
using Bookstore_Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bookstore_Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;

        }
        public IActionResult Index()
        {
            List<Product> ProductList = _productRepository.GetAll(includeProperty: "Category").ToList();
            return View(ProductList);
        }
        public IActionResult Create()
        {
            ProductVM productVM = new()
            {
                CategoryList = _categoryRepository.GetAll().ToList().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.ID.ToString(),
                }),
                product = new Product()
            };
            return View(productVM);
        }
        [HttpPost]
        public IActionResult Create(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");
                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    productVM.product.imageUrl = @"\images\product\" + fileName;
                }
                _productRepository.Add(productVM.product);
                _productRepository.Save();
                TempData["Success"] = "Product Cteated Sussessfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        //public IActionResult Upsert(int? id)
        //{
        //    if(id == null || id == 0)
        //    {
        //        return View();
        //    }
        //    Product product = _productRepository.Get(u=>u.Id == id);
        //    return View(product);
        //}
        //[HttpPost]
        //public IActionResult Upsert(Product product)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (product.Id == 0)
        //        {
        //            _productRepository.Add(product);
        //        }
        //        else
        //        {
        //            _productRepository.Update(product);
        //        }
        //        _productRepository.Save();
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}
        public IActionResult Update(int id)
        {
            ProductVM productVM = new()
            {
                CategoryList = _categoryRepository.GetAll().ToList().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.ID.ToString(),
                }),
            };
            Product products = _productRepository.Get(u => u.Id == id);
            productVM.product = products;
            return View(productVM);
        }
        [HttpPost]
        public IActionResult Update(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");
                    if (!string.IsNullOrEmpty(productVM.product.imageUrl))
                    {
                        var oldimagePath = Path.Combine(wwwRootPath, productVM.product.imageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldimagePath))
                        {
                            System.IO.File.Delete(oldimagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    productVM.product.imageUrl = @"\images\product\" + fileName;
                }
                _productRepository.Update(productVM.product);
                _productRepository.Save();
                TempData["Success"] = "Product Updated Sussessfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> ProductList = _productRepository.GetAll(includeProperty: "Category").ToList();
            return Json(new { data = ProductList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var producttobeDeleted = _productRepository.Get(u => u.Id == id);
            if (producttobeDeleted == null)
            {
                return Json(new { success = false, message = "error while deleting" });
            }
            var oldimagePath = Path.Combine(_webHostEnvironment.WebRootPath, producttobeDeleted.imageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldimagePath))
            {
                System.IO.File.Delete(oldimagePath);
            }
            _productRepository.Remove(producttobeDeleted);
            _productRepository.Save();
            return Json(new { success = true, message = "product deleted" });
        }
        #endregion

    }
}

Bookstore Web/Areas/Admin/Views/Company/Create.cshtml
@{
    ViewData["title"] = "Create Product";
}
@model Company
<div class="row justify-content-center">
    <div class="col-10">
        <div class="card shadow border-0 mt-4">
            <div class="card-header bg-secondary bg-gradient m-lg-0 py3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="text-white py-2">Create Company</h2>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <form method="post" class="row" enctype="multipart/form-data">
                    <input asp-for="Id" hidden value="0" />
                    <div class="row">
                        <div class="col-10">
                            <div class="border pt-3">
                                <div class="py-2">
                                    <input type="text" asp-for="Name" placeholder="Name" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="PhoneNumber" placeholder="PhoneNumber" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="StreetAddress" placeholder="StreetAddress" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="City" placeholder="City" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="City" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="State" placeholder="State" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="State" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="PostalCode" placeholder="PostalCode" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                                </div>
                                <div class="row mt-5">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-primary form-control">Create</button>
                                    </div>
                                    <div class="col-6">
                                        <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary form-control">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Bookstore Web/Areas/Admin/Views/Company/Index.cshtml
@{
    ViewData["title"] = "Company List";
}
@model List<Company>
<partial name="_Notification" />
<div class="row justify-content-center">
    <div class="col-10">
        <div class="card shadow border-0 mt-4">
            <div class="card-header bg-secondary bg-gradient m-lg-0 py3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="text-white py-2">Product List</h2>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div class="row justify-content-end mb-3">
                    <div class="col-6 text-end">
                        <a asp-controller="Company" asp-action="Create" class="btn btn-outline-primary rounded-3">
                            <i class="bi bi-plus-circle"></i> Create new Company
                        </a>
                    </div>
                </div>
                <table id="tblData" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Address</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Phone Number</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script src="~/js/Company.js"></script>
}

Bookstore Web/Areas/Admin/Views/Company/Update.cshtml
@{
    ViewData["title"] = "Create Product";
}
@model Company
<div class="row justify-content-center">
    <div class="col-10">
        <div class="card shadow border-0 mt-4">
            <div class="card-header bg-secondary bg-gradient m-lg-0 py3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="text-white py-2">Update Company</h2>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <form method="post" class="row" enctype="multipart/form-data">
                    <input asp-for="Id" hidden value="0" />
                    <div class="row">
                        <div class="col-10">
                            <div class="border pt-3">
                                <div class="py-2">
                                    <input type="text" asp-for="Name" placeholder="Name" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="PhoneNumber" placeholder="PhoneNumber" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="StreetAddress" placeholder="StreetAddress" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="City" placeholder="City" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="City" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="State" placeholder="State" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="State" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="PostalCode" placeholder="PostalCode" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                                </div>
                                <div class="row mt-5">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-primary form-control">Update</button>
                                    </div>
                                    <div class="col-6">
                                        <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary form-control">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Bookstore Web/Areas/Admin/Views/Company/Upsert.cshtml
@model Product
<div class="row justify-content-center">
    <div class="col-10">
        <div class="card shadow border-0 mt-4">
            <div class="card-header bg-secondary bg-gradient m-lg-0 py3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2 class="text-white py-2">@(Model.Id!=0?"Update":"Create") Category</h2>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <form method="post" class="row">
                    @* <input asp-for="Id" hidden value="0" /> *@
                    <div class="row">
                        <div class="col-10">
                            <div class="border pt-3">
                                <div class="py-2">
                                    <input type="text" asp-for="Title" placeholder="Title" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <textarea asp-for="Description" placeholder="Discription" class="form-control form-floating shadow border-0"></textarea>

                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="ISBN" placeholder="ISBN" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="ISBN" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="Author" placeholder="Author" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Author" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="number" asp-for="ListPrice" placeholder="ListPrice" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="ListPrice" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="Price" placeholder="Price for 1-50" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Price" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="Price50" placeholder="Price for 50+" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Price50" class="text-danger"></span>
                                </div>
                                <div class="py-2">
                                    <input type="text" asp-for="Price100" placeholder="Price for 100+" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="Price100" class="text-danger"></span>
                                </div>
                                @* <div class="py-2">
                                    <select asp-for="CategoryID" asp-items="ViewBag.Categori" class="form-control form-floating shadow border-0">
                                        <option disabled selected>
                                            --Select Category--
                                        </option>
                                    </select>
                                    <span asp-validation-for="CategoryID" class="text-danger"></span>
                                </div> *@
                                @* <div class="py-2">
                                    <input type="file" name="file" class="form-control form-floating shadow border-0" />
                                    <span asp-validation-for="imageUrl" class="text-danger"></span>
                                </div> *@
                                <div class="row mt-5">
                                    <div class="col-6">
                                        @if (Model.Id == 0)
                                        {
                                            <button type="submit" class="btn btn-primary form-control">Create</button>
                                        }
                                        else
                                        {
                                            <button type="submit" class="btn btn-primary form-control">Update</button>
                                        }
                                    </div>
                                    <div class="col-6">
                                        <a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary form-control">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @* <div class="col-2">
                            <p>image</p>
                        </div> *@
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}